# vim: filetype=yaml
name: TPC Queries with Ibis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tpc-queries:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        id: install_python
        with:
          python-version: "3.9"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: ./runtpc -i sqlite -i ibis

  tpc-queries-ibis-master:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        id: install_python
        with:
          python-version: "3.9"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip uninstall -y ibis-framework
      - run: pip install --upgrade 'git+https://github.com/ibis-project/ibis.git@master'
      - run: ./runtpc -i sqlite -i ibis

  duckdb-tpc-queries-ibis-master:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        id: install_python
        with:
          python-version: "3.9"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip uninstall -y ibis-framework
      - run: pip install --upgrade 'git+https://github.com/ibis-project/ibis.git@master'
      - run: python -c "import duckdb; con = duckdb.connect('tpch.ddb'); con.execute('CALL dbgen(sf=0.1);')"
      - run: ./runtpc -i duckdb -i ibis -d 'tpch.ddb' -b 'duckdb'
